export const MS_PER_DAY = 1000 * 60 * 60 * 24;
export const DAYS_IN_WEEK = 7;

export const ENGAGEMENT_SCORE_MAX = 100;
export const ENGAGEMENT_WEIGHT_PER_SALE = 10;
export const ENGAGEMENT_RECENCY_THRESHOLD_RECENT = 30;
export const ENGAGEMENT_RECENCY_BONUS_RECENT = 30;
export const ENGAGEMENT_RECENCY_THRESHOLD_MODERATE = 60;
export const ENGAGEMENT_RECENCY_BONUS_MODERATE = 15;

export const ABC_PERCENTILE_A = 0.2;
export const ABC_PERCENTILE_B = 0.5;
