// Material Design 3 color system — extracted from Stitch designs (purple scheme)
// Source of truth: Google Stitch project "Perfil do Cliente 360"

export const md3 = {
  light: {
    primary: "#6500C2",
    primaryContainer: "#8127E8",
    onPrimary: "#FFFFFF",
    onPrimaryContainer: "#E9D5FF",
    primaryFixed: "#EDDCFF",
    primaryFixedDim: "#D8BAFF",
    onPrimaryFixed: "#290055",
    onPrimaryFixedVariant: "#6200BC",

    secondary: "#70547F",
    secondaryContainer: "#EECBFE",
    onSecondary: "#FFFFFF",
    onSecondaryContainer: "#6F527E",
    secondaryFixed: "#F5D9FF",
    secondaryFixedDim: "#DDBAED",
    onSecondaryFixed: "#291038",
    onSecondaryFixedVariant: "#573C66",

    tertiary: "#753A00",
    tertiaryContainer: "#984D00",
    onTertiary: "#FFFFFF",
    onTertiaryContainer: "#FFD5B9",
    tertiaryFixed: "#FFDCC5",
    tertiaryFixedDim: "#FFB783",
    onTertiaryFixed: "#301400",
    onTertiaryFixedVariant: "#703700",

    error: "#BA1A1A",
    errorContainer: "#FFDAD6",
    onError: "#FFFFFF",
    onErrorContainer: "#93000A",

    surface: "#F8F9FB",
    surfaceDim: "#D9DADC",
    surfaceBright: "#F8F9FB",
    surfaceContainerLowest: "#FFFFFF",
    surfaceContainerLow: "#F3F4F6",
    surfaceContainer: "#EDEEF0",
    surfaceContainerHigh: "#E7E8EA",
    surfaceContainerHighest: "#E1E2E4",
    surfaceVariant: "#E1E2E4",
    surfaceTint: "#7E22E5",

    onSurface: "#191C1E",
    onSurfaceVariant: "#4C4355",
    onBackground: "#191C1E",
    background: "#F8F9FB",

    outline: "#7D7387",
    outlineVariant: "#CEC2D8",

    inverseSurface: "#2E3132",
    inverseOnSurface: "#F0F1F3",
    inversePrimary: "#D8BAFF",

    // Semantic (kept for backward compat)
    success: "#059669",
    successBg: "#ECFDF5",
    successText: "#065F46",
    warning: "#D97706",
    warningBg: "#FEF3C7",
    warningText: "#92400E",
    danger: "#DC2626",
    dangerBg: "#FEE2E2",
    dangerText: "#991B1B",
    info: "#2563EB",
    infoBg: "#E6F1FB",
    infoText: "#1E40AF",
  },
  dark: {
    primary: "#D8BAFF",
    primaryContainer: "#6500C2",
    onPrimary: "#3D0078",
    onPrimaryContainer: "#EDDCFF",
    primaryFixed: "#EDDCFF",
    primaryFixedDim: "#D8BAFF",
    onPrimaryFixed: "#290055",
    onPrimaryFixedVariant: "#6200BC",

    secondary: "#DDBAED",
    secondaryContainer: "#573C66",
    onSecondary: "#3F254E",
    onSecondaryContainer: "#F5D9FF",
    secondaryFixed: "#F5D9FF",
    secondaryFixedDim: "#DDBAED",
    onSecondaryFixed: "#291038",
    onSecondaryFixedVariant: "#573C66",

    tertiary: "#FFB783",
    tertiaryContainer: "#703700",
    onTertiary: "#462000",
    onTertiaryContainer: "#FFDCC5",
    tertiaryFixed: "#FFDCC5",
    tertiaryFixedDim: "#FFB783",
    onTertiaryFixed: "#301400",
    onTertiaryFixedVariant: "#703700",

    error: "#FFB4AB",
    errorContainer: "#93000A",
    onError: "#690005",
    onErrorContainer: "#FFDAD6",

    surface: "#131316",
    surfaceDim: "#131316",
    surfaceBright: "#39393C",
    surfaceContainerLowest: "#0E0E11",
    surfaceContainerLow: "#1B1B1E",
    surfaceContainer: "#1F1F23",
    surfaceContainerHigh: "#2A2A2D",
    surfaceContainerHighest: "#353538",
    surfaceVariant: "#49454E",
    surfaceTint: "#D8BAFF",

    onSurface: "#E5E1E6",
    onSurfaceVariant: "#CBC4CF",
    onBackground: "#E5E1E6",
    background: "#131316",

    outline: "#958E99",
    outlineVariant: "#49454E",

    inverseSurface: "#E5E1E6",
    inverseOnSurface: "#313033",
    inversePrimary: "#7E22E5",

    // Semantic
    success: "#6EE7B7",
    successBg: "#064E3B",
    successText: "#6EE7B7",
    warning: "#FCD34D",
    warningBg: "#78350F",
    warningText: "#FCD34D",
    danger: "#FCA5A5",
    dangerBg: "#7F1D1D",
    dangerText: "#FCA5A5",
    info: "#93C5FD",
    infoBg: "#1E3A5F",
    infoText: "#93C5FD",
  },
} as const;

// Legacy compat — maps old theme names to the single MD3 scheme
export const themes = {
  default: {
    light: {
      primary: md3.light.primaryContainer,
      primaryHover: "#9F5AED",
      primarySurface: md3.light.primaryFixed,
      primarySurfaceHover: md3.light.primaryFixedDim,
      accent: md3.light.onPrimaryFixed,
      bgPrimary: md3.light.surfaceContainerLowest,
      bgSecondary: md3.light.surfaceContainerLow,
      bgTertiary: md3.light.surface,
      textPrimary: md3.light.onSurface,
      textSecondary: md3.light.onSurfaceVariant,
      // ACH-010: darker than md3.light.outline (#7D7387 ≈ 4.2:1 on #FFF)
      // to meet WCAG AA 4.5:1 for body text. Keeps the purple tint.
      textTertiary: "#5A5261",
      borderPrimary: md3.light.outlineVariant,
      borderSecondary: md3.light.surfaceContainerHigh,
      borderTertiary: md3.light.surfaceContainerLow,
      success: md3.light.success,
      successBg: md3.light.successBg,
      successText: md3.light.successText,
      warning: md3.light.warning,
      warningBg: md3.light.warningBg,
      warningText: md3.light.warningText,
      danger: md3.light.danger,
      dangerBg: md3.light.dangerBg,
      dangerText: md3.light.dangerText,
      info: md3.light.info,
      infoBg: md3.light.infoBg,
      infoText: md3.light.infoText,
    },
    dark: {
      primary: md3.dark.primary,
      primaryHover: "#B07CF0",
      primarySurface: md3.dark.primaryContainer,
      primarySurfaceHover: "#2A1B45",
      accent: md3.dark.onPrimaryFixed,
      bgPrimary: md3.dark.surfaceContainerLowest,
      bgSecondary: md3.dark.surfaceContainerLow,
      bgTertiary: md3.dark.surface,
      textPrimary: md3.dark.onSurface,
      textSecondary: md3.dark.onSurfaceVariant,
      textTertiary: md3.dark.outline,
      borderPrimary: md3.dark.outlineVariant,
      borderSecondary: md3.dark.surfaceContainerHigh,
      borderTertiary: md3.dark.surfaceContainerLow,
      success: md3.dark.success,
      successBg: md3.dark.successBg,
      successText: md3.dark.successText,
      warning: md3.dark.warning,
      warningBg: md3.dark.warningBg,
      warningText: md3.dark.warningText,
      danger: md3.dark.danger,
      dangerBg: md3.dark.dangerBg,
      dangerText: md3.dark.dangerText,
      info: md3.dark.info,
      infoBg: md3.dark.infoBg,
      infoText: md3.dark.infoText,
    },
  },
} as const;

export type ThemeName = keyof typeof themes;
export type ThemeMode = "light" | "dark";
export type ThemeColors = typeof themes.default.light;
export type MD3Colors = { [K in keyof typeof md3.light]: string };

export const classificationColors = {
  A: { bg: "#ECFDF5", text: "#059669" },
  B: { bg: "#FEF3C7", text: "#D97706" },
  // ACH-010: #4B5563 (AAA-ish on #F3F4F6) replaces #6B7280 (AA-borderline).
  C: { bg: "#F3F4F6", text: "#4B5563" },
} as const;
